### ISSUE TITLE
Safari Main View

### ISSUE THREAD

**Issue by romansavchuk** [filingroove/wavescore-chat#1]
http://take.ms/OstBQ

**Comment by filingroove** [comment]
Also 
![screen shot 2016-09-21 at 6 24 52 pm](https://cloud.githubusercontent.com/assets/5341506/18717498/c9841660-8028-11e6-86e1-b269ef8a6c0d.png)

**Comment by filingroove** [comment]
It was an issue specific for Safari 10 in macOS Sierra. Fixed ;)
