### ISSUE TITLE
Group chat update

### ISSUE THREAD

**Issue by romansavchuk** [filingroove/wavescore-chat#54]
http://take.ms/YH3vX and http://take.ms/D06SH + all of the popups for that

**Comment by filingroove** [comment]
![image](https://cloud.githubusercontent.com/assets/5341506/19301968/e07bc26c-906a-11e6-8c1e-53e97927acc5.png)

![image](https://cloud.githubusercontent.com/assets/5341506/19301980/e91eefd4-906a-11e6-88fc-0fd9d50ad47a.png)

**Comment by filingroove** [comment]
- [ ] @Invite to Chat
- [ ] @Chat Title
- [ ] @Chat Image
- [ ] @Chat Members
- [ ] @Leave Chat
