### ISSUE TITLE
Chats creating flow

### ISSUE THREAD

**Issue by romansavchuk** [filingroove/wavescore-chat#55]
All placeholders from PSD like this one - http://take.ms/U1DSt  for big and minichat

![image](https://cloud.githubusercontent.com/assets/5341506/19301932/ac6fc518-906a-11e6-809b-6fdf2cb8a0e5.png)

+ 

Entire flow of creating chat: http://take.ms/ElUUU and following screens.

![image](https://cloud.githubusercontent.com/assets/5341506/19301945/bf95d25e-906a-11e6-8c92-2e879cc5b201.png)

**Comment by filingroove** [comment]
Working on it right now. Requires some rewriting :)
