### ISSUE TITLE
Creating Chat issues

### ISSUE THREAD

**Issue by romansavchuk** [filingroove/wavescore-chat#64]
http://take.ms/f0gGb
http://take.ms/ID6JK
http://take.ms/XqKYU
http://take.ms/VfQUk
http://take.ms/j4Low
http://take.ms/DG06G

**Comment by filingroove** [comment]
![image](https://cloud.githubusercontent.com/assets/5341506/19382117/6a0e13c0-9207-11e6-8351-cac402575e08.png)

**Comment by filingroove** [comment]
- [ ] 

![image](https://cloud.githubusercontent.com/assets/5341506/19382131/7dc1b124-9207-11e6-8750-05317ff47c52.png)

- [ ] 

![image](https://cloud.githubusercontent.com/assets/5341506/19382176/baaa3782-9207-11e6-90f3-5131d91d9f31.png)

- [ ] 

![image](https://cloud.githubusercontent.com/assets/5341506/19382193/cb4e6ebe-9207-11e6-9bd2-f35ad88ce155.png)

- [ ] 

![image](https://cloud.githubusercontent.com/assets/5341506/19382230/e9782fba-9207-11e6-99c7-f694761ba73d.png)

- [ ] 

![image](https://cloud.githubusercontent.com/assets/5341506/19382244/f8342e6e-9207-11e6-9855-b6c0dffbbe8b.png)
