### ISSUE TITLE
Events to group chat (theme changed, leave chat, etc.)

### ISSUE THREAD

**Issue by romansavchuk** [filingroove/wavescore-chat#67]
Make exactly like below:

1 - **Ferenc Fezler** was invited to chat by **Roman Savchuk**.
2 - **Ferenc Fezler** left chat.
3 - Photo was changed by **Roman Savchuk**.
4 - Title was changed by **Roman Savchuk**.

It will be same as date in chat like this - http://take.ms/WfT8I

**Comment by filingroove** [comment]
1, 2 done
