### ISSUE TITLE
Chat issues

### ISSUE THREAD

**Issue by romansavchuk** [filingroove/wavescore-chat#70]
http://take.ms/Kxb7t

**Comment by romansavchuk** [comment]
http://take.ms/yyWCw

long name of doc issue

**Comment by romansavchuk** [comment]
after chat creating - we should open created chat

**Comment by romansavchuk** [comment]
http://take.ms/iPNvg

**Comment by romansavchuk** [comment]
i can't send scorecard to chat

**Comment by filingroove** [comment]
> i can't send scorecard to chat

Popup opens after all images are loaded, but currently they can't be loaded :) This issue will fix itself.

![screen shot 2016-10-18 at 1 29 33 am](https://cloud.githubusercontent.com/assets/5341506/19458059/585fc86c-94d2-11e6-935b-51dc92247fde.png)

**Comment by filingroove** [comment]
> long name of doc issue

file name will now break even in multiple lines if it contains no spaces or dashes
![screen shot 2016-10-18 at 11 30 47 pm](https://cloud.githubusercontent.com/assets/5341506/19495441/0dd635a0-958c-11e6-8d0a-8f2e06ad2bfe.png)
![screen shot 2016-10-18 at 11 38 14 pm](https://cloud.githubusercontent.com/assets/5341506/19495447/111c1f2c-958c-11e6-8b3f-668715548de7.png)

**Comment by filingroove** [comment]
> http://take.ms/iPNvg

fixed for the third time )
