### ISSUE TITLE
Chat issues

### ISSUE THREAD

**Issue by romansavchuk** [filingroove/wavescore-chat#76]
http://take.ms/9JEvC

**Comment by romansavchuk** [comment]
http://take.ms/0PQRK

**Comment by romansavchuk** [comment]
http://take.ms/7OmXV

**Comment by romansavchuk** [comment]
http://www.giphy.com/gifs/l2JhF9J2RmNUI80Gk

**Comment by romansavchuk** [comment]
http://take.ms/d3xZo

**Comment by romansavchuk** [comment]
посмотри, очень странный баг в начале видео я хз с чем связано - http://take.ms/ptaxP

**Comment by romansavchuk** [comment]
http://take.ms/6NK6c

**Comment by romansavchuk** [comment]
http://take.ms/5R7SJ

**Comment by romansavchuk** [comment]
http://take.ms/B2NGi

**Comment by filingroove** [comment]
![](http://i.imgur.com/zDH28Mx.jpg)

Everything is done except this one comment.
Expect to close this issue today
