### ISSUE TITLE
Chat Issues part 2

### ISSUE THREAD

**Issue by romansavchuk** [filingroove/wavescore-chat#78]
http://take.ms/RRzvK

**Comment by romansavchuk** [comment]
http://take.ms/sdoF4

**Comment by romansavchuk** [comment]
http://take.ms/L8CaV

**Comment by romansavchuk** [comment]
http://take.ms/DptFa

**Comment by romansavchuk** [comment]
http://take.ms/a6VwH

**Comment by filingroove** [comment]
> http://take.ms/L8CaV

Most of this is done.

I mark everything that is done with 👍 , but video contains many issues :)

**Comment by romansavchuk** [comment]
http://take.ms/zItgY
