### ISSUE TITLE
Chat Remaining Issues

### ISSUE THREAD

**Issue by romansavchuk** [filingroove/wavescore-chat#79]
http://take.ms/20r1Q

![image](https://cloud.githubusercontent.com/assets/5341506/20033621/85f57ad0-a3ad-11e6-987f-a85278535546.png)

**Comment by romansavchuk** [comment]
http://take.ms/zbDJQ

**Comment by romansavchuk** [comment]
http://take.ms/zZ8ze

**Comment by romansavchuk** [comment]
http://take.ms/3yWDL

**Comment by romansavchuk** [comment]
http://take.ms/CUKZVX

**Comment by romansavchuk** [comment]
читай в чате - http://take.ms/9J48X

**Comment by romansavchuk** [comment]
убрать скрол, пока у нас одна строка - http://www.giphy.com/gifs/3o6ZtmPrnRadILC3uM

**Comment by romansavchuk** [comment]
так выглядит когда я зааплодил фото - http://take.ms/bMw2f

**Comment by romansavchuk** [comment]
а вот так, сразу после того как я закрыл меню аттачментов и подвигал окошко - http://take.ms/gbrrw

**Comment by romansavchuk** [comment]
http://take.ms/l5kNE

**Comment by romansavchuk** [comment]
а так, когда я нажал ентер - http://take.ms/0lzBK

**Comment by romansavchuk** [comment]
http://take.ms/rmClO

**Comment by romansavchuk** [comment]
http://take.ms/pse94

**Comment by romansavchuk** [comment]
http://take.ms/4txzA

**Comment by romansavchuk** [comment]
http://take.ms/Ez4Rq

**Comment by romansavchuk** [comment]
http://take.ms/zgVJ2

**Comment by romansavchuk** [comment]
http://take.ms/YbKwp

**Comment by romansavchuk** [comment]
критически большая задержка между тем как я нажал энтер, и тем как бар с атачментами и линкой пропал - http://www.giphy.com/gifs/3oz8xYIrPsulVqeWjK

**Comment by romansavchuk** [comment]
http://take.ms/aFiTr

**Comment by romansavchuk** [comment]
http://take.ms/GfgDy

**Comment by romansavchuk** [comment]
http://take.ms/nzpvI

**Comment by romansavchuk** [comment]
http://take.ms/I3e1A

**Comment by romansavchuk** [comment]
когда отодвинуто какое-то ссобщение - другое лагает - http://www.giphy.com/gifs/l0MYtsD1QUamMXIL6

**Comment by romansavchuk** [comment]
не стоит показывать теги (наверное) это может быть небезопасно (вставил туда скриптец какой-то и все)

**Comment by romansavchuk** [comment]
http://take.ms/RZxVk

**Comment by romansavchuk** [comment]
http://take.ms/gcfo6

**Comment by romansavchuk** [comment]
http://take.ms/30OWY

**Comment by romansavchuk** [comment]
http://take.ms/6t4NW

**Comment by romansavchuk** [comment]
убрать едит/делейт по клику на САМ балун, оставить на ховер с делеем и на зону (вне балуна) + сделать 50% при наведении на свои меседжи

**Comment by romansavchuk** [comment]
http://take.ms/RCUt5

**Comment by filingroove** [comment]
> http://take.ms/pse94

Выделяю в отдельный issue. Не смог отловить никак.

**Comment by filingroove** [comment]
> http://take.ms/YbKwp

С углами порешал, а вообще, это не баг, а фича. Я могу сделать, что бы быстрее линки рендерились, хоть мгновенно после того, как юзер отпустит клавишу. Делать?

**Comment by romansavchuk** [comment]
`http://take.ms/YbKwp`
С углами порешал, а вообще, это не баг, а фича. Я могу сделать, что бы быстрее линки рендерились, хоть мгновенно после того, как юзер отпустит клавишу. Делать?

**Comment by filingroove** [comment]
> http://take.ms/GfgDy

У меня во всех браузерах нормально работает. Дропзону добавлю

**Comment by filingroove** [comment]
> http://take.ms/I3e1A + сама проблема что неопредленные скоркарды

> убрать едит/делейт по клику на САМ балун, оставить на ховер с делеем и на зону (вне балуна) + сделать 50% при наведении на свои меседжи

На первом скрине тогда оставляю клик на весь bubble, потому что не будет открывать менюшку edit/delete. 

"+50%" это ты о чём?

**Comment by filingroove** [comment]
> http://take.ms/60Ajf

На ховер не логично. Вообще никто так не делает и получится, что человек просто наводит курсор на сообщение, что бы выделить текст, например, а сообщение от него убегает в сторону :) Нет способа следить за тем, чего хочет юзер от сообщения. Потому лучше такого не делать.

Остальное по скрину есть

**Comment by filingroove** [comment]
> http://take.ms/I3e1A + сама проблема что неопредленные скоркарды

Это решится, когда я АПИ индусов подключу. Просто без АПИ непонятно откуда брать эти скоркарды )
