### ISSUE TITLE
Chat issues 3

### ISSUE THREAD

**Issue by romansavchuk** [filingroove/wavescore-chat#83]
http://take.ms/Abhcp

**Comment by romansavchuk** [comment]
что-нибудь, что лучше подходит - http://take.ms/YiM3b

**Comment by romansavchuk** [comment]
http://take.ms/5LMiJ

**Comment by romansavchuk** [comment]
http://take.ms/VlEey

**Comment by romansavchuk** [comment]
http://take.ms/4IZp9

**Comment by romansavchuk** [comment]
http://take.ms/83el7

**Comment by romansavchuk** [comment]
про пикер - http://take.ms/k34RZ

**Comment by romansavchuk** [comment]
можем с этим что-то сделать? http://www.giphy.com/gifs/l3vR2ZgQUjQwBYUKc

**Comment by romansavchuk** [comment]
когда скроллил и потом начал вводить текст - то результаты не начинаются сначала списка а уехали со скроллом вверх - http://www.giphy.com/gifs/3oriO0FoHlgfkMUTja

**Comment by romansavchuk** [comment]
http://take.ms/yFT97

**Comment by romansavchuk** [comment]
http://take.ms/3pdOZ

**Comment by filingroove** [comment]
![image](https://cloud.githubusercontent.com/assets/5341506/20078342/cd798878-a548-11e6-932f-9e15070a6873.png)

Край ровный, просто большой. Можно сделать уже, но я ориентировался на PSD + меню аттачментов

**Comment by filingroove** [comment]
![image](https://cloud.githubusercontent.com/assets/5341506/20081065/db1621a0-a555-11e6-953d-2dbeabf994ce.png)

Я всё ещё не могу отловить у себя двойной ивент

**Comment by filingroove** [comment]
> можем с этим что-то сделать? http://www.giphy.com/gifs/l3vR2ZgQUjQwBYUKc

С этим, пока что, ничего. Тут нужно придумывать хороший массивный костыль. Вынесу отдельно, что бы не забыть, но прямо сейчас лучше доделать всю мелочь и отдать уже
