### ISSUE TITLE
Chat Issues v4

### ISSUE THREAD

**Issue by romansavchuk** [filingroove/wavescore-chat#85]
http://take.ms/YjvO1

**Comment by romansavchuk** [comment]
http://take.ms/svnGD

**Comment by romansavchuk** [comment]
http://take.ms/ioi0o

**Comment by romansavchuk** [comment]
http://take.ms/PyhOs

**Comment by romansavchuk** [comment]
не аплоадит фотки

**Comment by romansavchuk** [comment]
http://take.ms/jODxVi

**Comment by romansavchuk** [comment]
http://take.ms/9Or3t

**Comment by romansavchuk** [comment]
http://take.ms/ykLaV

**Comment by romansavchuk** [comment]
http://take.ms/ol9tL

**Comment by romansavchuk** [comment]
12/24 не работает, у меня стоит 12 часовой формат но ам/пм не появилось и показывает 23 часа и тд

**Comment by romansavchuk** [comment]
когда я написал и выбрал кого-то то буква "а" не должна оставаться, а должна появляться серая стандартная надпись - http://take.ms/ol9tL + тут не грузит фотки опять

**Comment by romansavchuk** [comment]
http://take.ms/H6hk4

**Comment by filingroove** [comment]
> http://take.ms/jODxVi

Undefined пропадёт после адаптации. Сейчас просто пытается загрузить из базы юзера, которого там нет.

**Comment by filingroove** [comment]
> 12/24 не работает, у меня стоит 12 часовой формат но ам/пм не появилось и показывает 23 часа и тд

А ты страницу перезагружал? Там нужно перезагрузить. Что бы не перезагружало, там сложно сделать. Если и делать, то не прямо сейчас. 

Да, нужно какой-то месседж, что нужно будет перезагрузить страницу или перезагружать автоматически и сразу

**Comment by filingroove** [comment]
> http://take.ms/ol9tL

Подсвечивать совпадение пока не можем. Сможем к следующему релизу. Просто сильно долго и не критично сейчас

**Comment by filingroove** [comment]
> http://take.ms/ykLaV

Попробовал сделать тултип, но в силу особенностей именно того элемента с иконками, он там не влазит и влазить не может. Вообще никак. Потому сделаю стандартный попап сейчас

![screen shot 2016-11-10 at 12 28 47 pm](https://cloud.githubusercontent.com/assets/5341506/20173301/5e20df12-a741-11e6-8927-bd14ad42af9f.png)

**Comment by filingroove** [comment]
> когда я написал и выбрал кого-то то буква "а" не должна оставаться, а должна появляться серая стандартная надпись - http://take.ms/ol9tL + тут не грузит фотки опять

Ты два одинаковых скрина кинул :) 

Я правильно понял, что ты про выбор юзера при создании чата?

**Comment by filingroove** [comment]
> когда я написал и выбрал кого-то то буква "а" не должна оставаться, а должна появляться серая стандартная надпись

Да, это я правильно понял и запилил

**Comment by filingroove** [comment]
Осталось только вот это

> не аплоадит фотки и документы
> просто ничего не происходит

Смотрю и потом закрою. Будет быстро
