### ISSUE TITLE
Chat Integration Issues

### ISSUE THREAD

**Issue by romansavchuk** [filingroove/wavescore-chat#87]
Completed but i can't remove this.

**Comment by romansavchuk** [comment]
http://take.ms/arw5l

**Comment by romansavchuk** [comment]
Close popup of uploading immediately after drag&drop or selecting file AND fix (show progress of uploading)

**Comment by romansavchuk** [comment]
http://take.ms/8qnNi - maybe show the same view as we have for links w/o richlink data, justa with a (x) on top?

**Comment by romansavchuk** [comment]
http://take.ms/u2tPI

**Comment by romansavchuk** [comment]
http://take.ms/1J7nb

**Comment by romansavchuk** [comment]
http://take.ms/H4vuw

**Comment by romansavchuk** [comment]
http://take.ms/WYdCg

**Comment by romansavchuk** [comment]
http://take.ms/JCLed + in my account - nothing changed in zenduja vault

**Comment by romansavchuk** [comment]
Forever loading for Location.

**Comment by romansavchuk** [comment]
Forever loading for Scorecards.

**Comment by romansavchuk** [comment]
http://take.ms/nWLJb

**Comment by romansavchuk** [comment]
http://take.ms/AMzqW

**Comment by romansavchuk** [comment]
http://take.ms/t9N8w - after i open chat on the Sandy's side, and then click close minichat - it shows me double check in the chat's menu, but actually i didn't open it from MY side (but maybe you read this message instead of me)

**Comment by romansavchuk** [comment]
http://take.ms/kuULu

**Comment by romansavchuk** [comment]
http://take.ms/gtI1n

**Comment by romansavchuk** [comment]
http://take.ms/N0dUF

**Comment by romansavchuk** [comment]
http://take.ms/ZiNnx

**Comment by romansavchuk** [comment]
http://take.ms/tp0hb

**Comment by romansavchuk** [comment]
http://take.ms/Llwm7

**Comment by romansavchuk** [comment]
no animation here - http://take.ms/A4NUo

**Comment by romansavchuk** [comment]
http://take.ms/PfDHu

**Comment by romansavchuk** [comment]
http://take.ms/azY4X

**Comment by romansavchuk** [comment]
http://take.ms/KTh9l - i got that. It showed ALL members for my circle

**Comment by romansavchuk** [comment]
last priority - http://take.ms/hhv7E

**Comment by romansavchuk** [comment]
http://take.ms/ytcXR

**Comment by romansavchuk** [comment]
http://take.ms/v8O3Z

**Comment by romansavchuk** [comment]
http://take.ms/a7mqf

**Comment by romansavchuk** [comment]
Minichat not working on videopages

**Comment by romansavchuk** [comment]
http://take.ms/gapek

**Comment by romansavchuk** [comment]
emails like "blabla@mail.com" shouldn't be like rich link

**Comment by romansavchuk** [comment]
It should delete richlink after first delete - http://www.giphy.com/gifs/l3vR9Qb5Wb6hBA1Vu

**Comment by romansavchuk** [comment]
http://take.ms/06ly8

**Comment by romansavchuk** [comment]
When i open the page, i see chat icon with red dot on top for some seconds (even if i have no unread messages)

**Comment by romansavchuk** [comment]
email links in chat should redirect to **mailto:**mail@mail.com to click and open mail app :)

**Comment by romansavchuk** [comment]
http://take.ms/QmqLY

**Comment by romansavchuk** [comment]
http://take.ms/RWkAl

**Comment by romansavchuk** [comment]
http://take.ms/X8c55

**Comment by romansavchuk** [comment]
http://take.ms/8ELC3

**Comment by romansavchuk** [comment]
http://take.ms/gGYgT

**Comment by romansavchuk** [comment]
http://take.ms/raVz3

**Comment by romansavchuk** [comment]
http://take.ms/yLnwVl

**Comment by romansavchuk** [comment]
http://take.ms/k10uC

**Comment by romansavchuk** [comment]
http://take.ms/GvlVc

**Comment by romansavchuk** [comment]
http://take.ms/tNVKV

**Comment by romansavchuk** [comment]
http://take.ms/82rPO

**Comment by romansavchuk** [comment]
http://take.ms/XgXzZ

**Comment by romansavchuk** [comment]
When i click on chat icon in menu and open a chat - here too much time of loading, we should show minichat window immediately, and after that load messages history

**Comment by romansavchuk** [comment]
shoud be "autoscrolldown" here - http://www.giphy.com/gifs/3oz8xFdhEwrquXG4X6

**Comment by filingroove** [comment]
The last two will be a separate issue. Will work on that after everything else is fixed as it requires rewriting some core logic

**Comment by tomanimaran** [comment]
http://take.ms/PfDHu -- done
![issue1](https://cloud.githubusercontent.com/assets/23522598/20388651/df4037fa-aceb-11e6-8d45-e9ecd45540df.jpg)

**Comment by filingroove** [comment]
> http://take.ms/nWLJb
>
> Yurii: Issue on my side

I made a mistake, issue is with header.scss on staging. On rundewoo.com it looks okay.

@tomanimaran, please, update class .header-icon.has-unread

It looks like this on my side

```scss
@mixin header-icon-image($class) {
	&.#{$class} {

		@include svg-bg('../img/#{$class}');

		background-size: 32px;
		background-repeat: no-repeat;
		background-position: center;

		&:hover {
			background-color: rgba(#fff, 0.1);
		}

		position: relative;

		&.has-unread {

			@include svg-bg('../img/icons/#{$class}-has-unread-active');

			opacity: 1;

			background-size: 32px;
			background-repeat: no-repeat;
			background-position: center;

			border: none;
			outline: none;

			&:hover {
				background-color: rgba(#fff, 0.1);
			}

			&.active {
				@include svg-bg('../img/icons/#{$class}-has-unread-active');
				background-color: rgba(#fff, 0.1);
			}

		}
	}
}
```

**Comment by tomanimaran** [comment]
http://take.ms/RWkAl
![capture](https://cloud.githubusercontent.com/assets/23522598/20390035/d1b87370-acf2-11e6-8d66-2fc99364b607.JPG)

**Comment by romansavchuk** [comment]
http://take.ms/RFGtJ

**Comment by romansavchuk** [comment]
http://take.ms/ERUia

**Comment by romansavchuk** [comment]
http://take.ms/T3LSc

**Comment by romansavchuk** [comment]
http://take.ms/Le5Ws

**Comment by romansavchuk** [comment]
http://take.ms/s5QIX

**Comment by romansavchuk** [comment]
if type and send while loading - http://take.ms/Egszt

**Comment by filingroove** [comment]
@tomanimaran 

One significant change regarding gif uploads in `dev/js/file-upload.js`

```js
//  Around line 36
xhr.onreadystatechange = function( e ) {
    if ( xhr.readyState == 4 && xhr.status == 200 ) {
        let data = response.message;

        //  Edits start
        if ( data.type == 'gif' ) {
            $.post( `${uri}/gif`, data )
            .done( ( res ) => {
                if ( res.error ) {
                    console.error( error );
                    return;
                }

                if ( typeof callback == "function" ) {
                    callback( data, fileID );
                } else {
                    console.log( data, fileID );
                }
            } )

            return;
        }

        //  Edits end

        if ( typeof callback == "function" ) {
            callback( data, fileID );
        } else {
            console.log( data, fileID );
        }

    }
};
```

**Comment by filingroove** [comment]
@tomanimaran, I also strongly advise you to use SCSS with the gulp tasks provided to significantly speed up necessary changes. 

Please, see `instructions/project-structure.html` for details

**Comment by tomanimaran** [comment]
@tomanimaran, please, check what's wrong with this button. It's working fine on test site
your test site in chrome,firefox look like 
![capture3](https://cloud.githubusercontent.com/assets/23522598/20421561/ace3e492-ad8a-11e6-8bfc-b292d933765c.JPG)

**Comment by romansavchuk** [comment]
emails problem comes back - http://take.ms/yVHsh

**Comment by romansavchuk** [comment]
http://take.ms/8z5QB

**Comment by romansavchuk** [comment]
make links working - http://take.ms/vvp2J

**Comment by romansavchuk** [comment]
i am not sure that notification and notification sounds are working.

**Comment by filingroove** [comment]
@tomanimaran, your remaining tasks:

[ ] https://github.com/filingroove/wavescore-chat/issues/87#issuecomment-261063953

[ ] `messaging_page.css:12777`
```css
#show-chat-preferences, #show-messaging-preferences {
	...
	margin-top: -16px;
	...
}
```

[ ] Fans, Circle and Following popups are not working on `/messaging`

[ ] Bug Report ( Feedback ) implementation

Just link those files as mentioned in readme.md

[ ] Chats not opening on .quick-chat-open click

```js
working on it, please, wait
```

**Comment by tomanimaran** [comment]
1.#87 (comment) -- done
2.messaging_page.css:12777 --done
3.Fans, Circle and Following popups are not working on /messaging -- done
4.Bug Report ( Feedback ) implementation -- done

**Comment by romansavchuk** [comment]
@tomanimaran 

1 - not working for me

**Comment by filingroove** [comment]
@tomanimaran, `http://104.154.114.112/wavescore-2.0/js/feedback.js` is missing. Please, check if it's there

**Comment by romansavchuk** [comment]
http://take.ms/ZHj5g

**Comment by romansavchuk** [comment]
chat preferences not working.

i changed time 12 - 24, but nothing changed

**Comment by filingroove** [comment]
@tomanimaran 

Here's the recent of changes. It includes fixes for messaging preferences and new "Coming Soon" popup design

A link to files: https://drive.google.com/drive/folders/0Bwa1sXF9qcnxQVFxaHV0OVN1SVk?usp=sharing

# `chat-settings-popups.js`

You need to replace old `popups.betaInfo` with the new one. I think it's the part of `chat.js` on your side. I changed quite a bit, so you can just copy the entire thing and replace the old one. 

Next line was added 

```js
popups.messagingPreferences = ( function() {
	...
	function save( e ) {
    	e.preventDefault();	// This one
    	document.cookie = `messaging-preferences-local=${ JSON.stringify( $('#messaging-preferences form').serializeFormJSON() ) }`;
    	chatSettingsPopups.hide();
    }
	...
} )();
```

# `chat.js`

Sounds are now loaded on init rather than on chat function evaluation.

```js
let chat = ( function() {
	...

	let incoming = new Audio();
	incoming.setAttribute("type", "audio/mpeg");
	incoming.setAttribute("src", 'sounds/incoming.mp3');

	let outgoing = new Audio();
	outgoing.setAttribute("type", "audio/mpeg");
	outgoing.setAttribute("src", 'sounds/outgoing.mp3');
	
	/*

		INIT START

	*/

	//	Takes care of options set in common/env.js
	//	After env is loaded, load socket.io
	function load() {
		apiURL = env[ env.now ].chatAPIurl;

		loadSocketIO();
		incoming.load();
		outgoing.load();
	}

	...
} )();
```

# `chat-attachments-popups.scss`

`#beta-info` is updated with new styles. It should affect the `#beta-info` in every page-specific **CSS**

**Comment by romansavchuk** [comment]
emails problem comes back - http://take.ms/yVHsh but probably it's because server speed because it's working from time to time

**Comment by filingroove** [comment]
@tomanimaran, here are new found issues:

## Click on "Submit" button should close the feedback popup

I updated `feedback.js`, you can get it here: https://drive.google.com/drive/folders/0Bwa1sXF9qcnxTWF4ZVFPa0R3czA?usp=sharing

## Delegate event listener for quick chat doesn't work

On staging, the issue persists with `ReferenceError: Can't find variable: requestCreateChatMy`

![screen shot 2016-11-19 at 11 41 45 am](https://cloud.githubusercontent.com/assets/5341506/20454568/3e699b7e-ae4d-11e6-812a-23ea99ffff79.png)
